package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Positive'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Positive")) {
    expectSteps {
        script {
            scriptContent = "exit 0"
        }
        script {
            scriptContent = """
                echo a
                exit 4
            """.trimIndent()
        }
    }
    steps {
        update<ScriptBuildStep>(1) {
            clearConditions()
            scriptContent = """
                echo a
                exit 5
            """.trimIndent()
        }
    }
}
