package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'HttpsGithubComChubatovaTigerChubatovaGradleTestsBackup'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("HttpsGithubComChubatovaTigerChubatovaGradleTestsBackup")) {
    val expected = GitVcsRoot({
        id("HttpsGithubComChubatovaTigerChubatovaGradleTestsBackup")
        name = "https://github.com/ChubatovaTiger/ChubatovaGradleTestsBackup"
        url = "https://github.com/ChubatovaTiger/ChubatovaGradleTestsBackup"
        branch = "refs/heads/master"
        param("useAlternates", "")
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        userForTags = "ChubatovaTiger"
        checkoutPolicy = GitVcsRoot.AgentCheckoutPolicy.NO_MIRRORS
    }

}
