package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'HttpsGithubComAChubatovaCheckpers'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("HttpsGithubComAChubatovaCheckpers")) {
    val expected = GitVcsRoot({
        id("HttpsGithubComAChubatovaCheckpers")
        name = "https://github.com/AChubatova/checkpers"
        url = "https://github.com/AChubatova/checkpers"
        branch = "refs/heads/main"
        param("useAlternates", "")
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        userForTags = "ChubatovaTiger"
        checkoutPolicy = GitVcsRoot.AgentCheckoutPolicy.NO_MIRRORS
    }

}
